apiVersion: batch/v1
kind: Job
metadata:
  name: lambda-csv-batch
  namespace: dev
spec:
  template:
    spec:
      containers:
        - name: lambda-csv-batch-ctr
          image: 05261977/csv-batch:v1
          command: ["python", "processor.py"]
          envFrom:
            - secretRef:
                name: database-config
      restartPolicy: OnFailure