# Wraps your Job into a schedule
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-daily-cron
  namespace: dev
spec:
  schedule: "0 0 * * *"  # Every day at midnight
  timeZone: "America/New_York"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lambda-csv-batch-ctr
            image: 05261977/csv-batch:v1
            envFrom:
              - secretRef:
                  name: database-config
          restartPolicy: OnFailure
