# airflow-entrypoint-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-entrypoint
  namespace: dev
data:
  entrypoint.sh: |
    #!/bin/bash
    set -ex

    echo '=== DEBUGGING CONNECTIVITY ==='
    echo "Testing connection to ${DB_HOST}:${DB_PORT}..."

    # Wait for PostgreSQL with retries
    until pg_isready -h ${DB_HOST} -U ${DB_USER}; do
      echo "Waiting for database..."
      sleep 2
    done

    # Test database connection
    echo 'Testing database connection...'
    export PGPASSWORD=${DB_PASSWORD}
    psql -h ${DB_HOST} -U ${DB_USER} -d ${DB_NAME} -c 'SELECT 1;' || echo 'Database connection failed'
    export PGPASSWORD=""

    echo '=== STARTING AIRFLOW ==='

    echo 'Verifying pip installation...'
    which pip

    echo 'Installing required providers...'
    pip install --no-cache-dir --upgrade pip
    pip install --no-cache-dir "apache-airflow-providers-docker>=3.12.0" "apache-airflow-providers-postgres>=5.0.0"

    echo 'Initializing Airflow database...'
    airflow db init

    echo 'Creating admin user...'
    airflow users create \
      --username admin \
      --password admin \
      --firstname Admin \
      --lastname User \
      --role Admin \
      --email admin@example.com || echo 'User already exists'

    airflow webserver --port 8080 &
    exec airflow scheduler