apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
stringData:
  PROTON_EMAIL: info@pubmerge.com
  PROTON_SMTP_TOKEN: 2XCTMMQB68CRG6DN
  FERNET_KEY: TrpFV5M4TmpWi4UxLXH90Trv_LttJL8S-_TcTZGus7U=
  AIRFLOW__WEBSERVER__SECRET_KEY: 9f2b3a6c4d18e9f9ad82f58d12c0e5a1c8e7d83f4d9a64c1f5e3b82c4f123456

