apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-consumer
  namespace: dev
  labels:
    app: lambda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command: [ 'sh', '-c', 'until nc -z kafka-service 9092; do echo "waiting for kafka..."; sleep 2; done' ]
      containers:
        - name: lambda-consumer-ctr
          image: 05261977/consumer:v2
          command: ["python", "consumer.py"]
          envFrom:
            - secretRef:
                name: database-config
          env:
            - name: POSTGRES_URL
              value: http://lambda-postgres:5432