apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-csv-batch
  namespace: dev
  labels:
    app: lambda
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda
  template:
    metadata:
      labels:
        app: lambda
    spec:
      containers:
        - name: lambda-csv-batch-ctr
          image: 05261977/csv-batch:v1
          command: ["sleep", "infinity"]
          envFrom:
            - secretRef:
                name: database-config