apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-db-setup
  namespace: dev
  labels:
    app: lambda-db-setup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda-db-setup
  template:
    metadata:
      labels:
        app: lambda-db-setup
    spec:
      containers:
        - name: 	lambda-db-setup-ctr
          image: 	05261977/db-setup:v1
          command: ["python", "db-init.py"]
          envFrom:
            - secretRef:
                name: database-config