apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-pgadmin
  namespace: dev
  labels:
    app: lambda-pgadmin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda-pgadmin
  template:
    metadata:
      labels:
        app: lambda-pgadmin
    spec:
      containers:
        - name: lambda-pgdamin-ctr
          image: dpage/pgadmin4
          envFrom:
            - secretRef:
                name: database-config
          ports:
          - containerPort: 5050