apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-postgres
  namespace: dev
  labels:
    app: lambda-postgres
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda-postgres
  template:
    metadata:
      labels:
        app: lambda-postgres
    spec:
      containers:
        - name: lambda-postgres-ctr
          image: postgres:15
          envFrom:
            - secretRef:
                name: database-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
