apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-producer-stream
  namespace: dev
  labels:
    app: lambda-producer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lambda-producer
  template:
    metadata:
      labels:
        app: lambda-producer
    spec:
      containers:
        - name: lambda-producer-ctr
          image: 05261977/producer-stream:v1
          command: ["python", "producer.py"]
