    apiVersion: v1
    kind: Service
    metadata:
      name: kafka-service
      namespace: dev
    spec:
      selector:
        app: lambda-kafka
      ports:
        - protocol: TCP
          port: 9092
          targetPort: 9092
      type: ClusterIP