    apiVersion: v1
    kind: Service
    metadata:
      name: lambda-pgadmin
      namespace: dev
    spec:
      selector:
        app: lambda-pgadmin
      ports:
        - protocol: TCP
          port: 5050
          targetPort: 80
          nodePort: 30050
      type: NodePort